import type { Village } from '@clearsignal/fusion';

/**
 * Kodagu villages used by the v1 demo. Centroids are approximate (±500 m),
 * taken from OSM place nodes; taluka is the 2018 three-taluka division.
 * Population figures are Census 2011 rounded, where known.
 * The bootstrap script seeds the same list into `village_geometries`.
 */
export const VILLAGES: readonly Village[] = [
  {
    village_id: 'kdg-makkandur',
    place_name: 'Makkandur',
    taluka: 'Madikeri',
    lat: 12.4632,
    lon: 75.7628,
    population: 2400,
  },
  {
    village_id: 'kdg-mukkodlu',
    place_name: 'Mukkodlu',
    taluka: 'Madikeri',
    lat: 12.4905,
    lon: 75.7413,
    population: 900,
  },
  {
    village_id: 'kdg-hattihole',
    place_name: 'Hattihole',
    taluka: 'Madikeri',
    lat: 12.5236,
    lon: 75.7322,
    population: 700,
  },
  {
    village_id: 'kdg-bhagamandala',
    place_name: 'Bhagamandala',
    taluka: 'Madikeri',
    lat: 12.3858,
    lon: 75.5333,
    population: 3100,
  },
  {
    village_id: 'kdg-talakaveri',
    place_name: 'Talakaveri',
    taluka: 'Madikeri',
    lat: 12.3861,
    lon: 75.4948,
    population: 300,
  },
  {
    village_id: 'kdg-jodupala',
    place_name: 'Jodupala',
    taluka: 'Madikeri',
    lat: 12.4935,
    lon: 75.6412,
    population: 600,
  },
  {
    village_id: 'kdg-madenadu',
    place_name: 'Madenadu',
    taluka: 'Madikeri',
    lat: 12.4562,
    lon: 75.6655,
    population: 1500,
  },
  {
    village_id: 'kdg-galibeedu',
    place_name: 'Galibeedu',
    taluka: 'Madikeri',
    lat: 12.4318,
    lon: 75.6856,
    population: 1800,
  },
  {
    village_id: 'kdg-monnangeri',
    place_name: 'Monnangeri',
    taluka: 'Madikeri',
    lat: 12.5071,
    lon: 75.6689,
    population: 500,
  },
  {
    village_id: 'kdg-kalur',
    place_name: 'Kalur',
    taluka: 'Madikeri',
    lat: 12.476,
    lon: 75.7069,
    population: 1100,
  },
  {
    village_id: 'kdg-napoklu',
    place_name: 'Napoklu',
    taluka: 'Madikeri',
    lat: 12.3067,
    lon: 75.7222,
    population: 5200,
  },
  {
    village_id: 'kdg-madikeri',
    place_name: 'Madikeri',
    taluka: 'Madikeri',
    lat: 12.4244,
    lon: 75.7382,
    population: 33000,
  },
  {
    village_id: 'kdg-sampaje',
    place_name: 'Sampaje',
    taluka: 'Madikeri',
    lat: 12.5003,
    lon: 75.5712,
    population: 2600,
  },
  {
    village_id: 'kdg-somwarpet',
    place_name: 'Somwarpet',
    taluka: 'Somwarpet',
    lat: 12.5977,
    lon: 75.8511,
    population: 7800,
  },
  {
    village_id: 'kdg-kushalnagar',
    place_name: 'Kushalnagar',
    taluka: 'Somwarpet',
    lat: 12.4575,
    lon: 75.9594,
    population: 15500,
  },
  {
    village_id: 'kdg-suntikoppa',
    place_name: 'Suntikoppa',
    taluka: 'Somwarpet',
    lat: 12.4563,
    lon: 75.8312,
    population: 6000,
  },
  {
    village_id: 'kdg-shanivarsanthe',
    place_name: 'Shanivarsanthe',
    taluka: 'Somwarpet',
    lat: 12.7296,
    lon: 75.8706,
    population: 4000,
  },
  {
    village_id: 'kdg-virajpet',
    place_name: 'Virajpet',
    taluka: 'Virajpet',
    lat: 12.1966,
    lon: 75.8053,
    population: 17200,
  },
  {
    village_id: 'kdg-siddapur',
    place_name: 'Siddapur',
    taluka: 'Virajpet',
    lat: 12.3033,
    lon: 75.8664,
    population: 8000,
  },
  {
    village_id: 'kdg-ponnampet',
    place_name: 'Ponnampet',
    taluka: 'Virajpet',
    lat: 12.1462,
    lon: 75.9429,
    population: 6300,
  },
];

/** Kodagu district bounding box (W, S, E, N) — used by adapters and the map. */
export const KODAGU_BBOX = [75.4, 11.9, 76.2, 12.9] as const;
